---
title: "regresstion of Stringr"
author: "Boon Hong"
date: "October 20, 2018"
output:
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup , include=FALSE}
library(tidyverse)
options(prompt = "$ ",digits = 11)
knitr::opts_chunk$set(fig.width = 5,fig.height = 5,out.width = 5,out.height = 5)
```

```{r}
x <- "\u00b5"
x %>% 
writeLines()
getOption("timeout")
options(timeout = "100")
getOption("timeout")
```

```{r str_c}
x <- LETTERS[1:3]
y <- letters[1:3]
str_c("|",x,y,sep = ",","|")
birthday <-T
str_c(
  "Mary ","good morning",
  if(birthday)" and Happy Birthday ...",
  "."
)

str_c(x,collapse = ",")
```

```{r}
x <- c("Apple","Banana","Pear")
str_sub(x,2,3)  
args(str_sub)

```
start and end 第2個 char start , 3 .. 

```{r}
x <- c("apple","banana","pear")
str_view(x,"a.")

```

正規式堶戚n\ ，在因字串中轉義 所以再加一個

```{r test}
dot <- ("a\\.b")
writeLines(dot)
```

```{r}
fruit %>% 
  str_view("(..)\\1",match = T)
```


? 是懶惰模式
```{r}
"1888 is the longest year in Roman numberals: MDCCCLXXXVIII" %>% 
  str_view("C[LX]+?")   
```

banana 沒有 "e" 
```{r}
c("apple","banana","pear") %>% 
  str_detect("e")
```

```{r}
words %>% 
  str_detect("^t") %>% 
  sum
```

subset 抽出來 子集合
```{r}
words %>% 
  str_subset("^t") %>% 
  head

```

匹配不會重???

```{r}
str_count(words,"a")
```


把 生成的字典 match sentences

```{r}

sentences %>% 
  length()

colors <- c("red","orange","yellow","green","blue","purple")
str_c(colors,collapse = "|") -> colors
str_subset(sentences,colors) -> has_color 
# str_extract(has_color,colors)
str_extract_all(has_color,colors,simplify = TRUE) %>% 
  head  # simplify trans to matrix  
str_subset(sentences,colors) %>% 
  str_view_all(colors)

```
str_extract 取出第一個匹配 ， 第二個不取

```{r}

tibble(sentences) %>% 
  tidyr::extract(
    sentences,
    c("article","noun"),
    "(a|the)([^ ]+)",
    remove = FALSE )

```

extract == str_extract 

```{r}

x <- c("apple","pear","banana")
str_replace(x,"[aeiou]","-")
str_replace_all(x,"[aeiou]","-")
```

replace pattern 可以用像是  c(1="one",2="two") 多字元

str_replace("","\\1 \\3 \\2") \\1 是第一字串的位置 ， 目前只有2跟3位置改變


```{r}
x <- "this is a sentence . this is another sentence ."
str_view_all(x,boundary("word"))
str_split(x,boundary("word")) 
```

```{r}
x <- c("banana","BANANA","banaNA")
str_view_all(x,regex("banana",ignore_case = T))
```

ignore_case = T 無論大小寫都要 regex("banana") == "banana"

multiline = T 是在 regex101 看到的 ， 是每個字串比較 ， 不是整個字串





