---
title: "Sma anlaysis"
author: "Boon Hong"
date: "December 12, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}

source("pgload.R")
search()

```

import 2317 股票

并且做資料調整

```{r}

import("TW2317.csv") %>% 
  as.tibble() -> df 

names(df) <- c("date","open","high","low","close","adj","vol") 

df %<>% 
  mutate(
    date = dmy(date)
  ) 
df %>% 
  is.na() %>% 
  which((.)==T)

df %>% 
  summary()

as.numeric(df$open) %>% 
  is.na %>% which((.)==T)

df %<>%
  mutate_if(
    is.character , as.numeric
  ) %>% 
  na.omit()

```

成交量為0 的數據 需要淘汰?

決策條件 
 黃金交叉 => 短均交于長均
 死亡交叉 => 長均交于短均

```{r}
i.short <- 5 
i.long <- 30 

df %<>%
  mutate(
    scl = SMA(close,i.short) ,
    scl1 = lag(scl,1) ,
    lcl = SMA(close,i.long) ,
    lcl1 = lag(lcl,1)
  )
  
```

```{r}

df %<>%
  # head
  mutate(
    gold = if_else(
      lcl1 > scl1 & scl > lcl ,1 , 0) ,
    death = if_else(
       scl1 > lcl1 & lcl > scl , -1 , 0)
  ) %>% 
  mutate(
    gold = if_else(gold==0,1000,lag(open,1)) ,
    death = if_else(death==0,1000,lag(open,1))
  ) %>% 
  na.omit()  %>%
  mutate(
    gold = gsub(1000,NA,gold) , 
    death = gsub(1000,NA,death) , 
    gold = as.numeric(gold) * 0.97 , 
    death = as.numeric(death) *1.03 , 
    gold = lead(gold,1),
    death = lead(death,1)
  )

```

```{r}
df %>% 
  filter(date > "2018-05-01") %>%
  mutate(
    tp = if_else(close-open>0,"up","down")
    ) %>% 
  gather(`scl`,`lcl`,key = "type",value = "price" ) %>% 
  ggplot(aes(date)) +
    geom_pointrange(
      aes(
        y= close ,
        ymax = high , 
        ymin = low,color = tp
      ), shape = 3 
    ) + 
    geom_line(aes(y=price,color = type))+
    geom_point(aes(y=gold),shape = 2,size = 3) + 
    geom_point(aes(y=death),shape = 6 , size = 3) -> p
ggplotly(p)

```

策略績效表現衡量的指標，大致上有：

1.平均報酬率
3.勝率
4.報酬率標準差
5.最大報酬率
6.最小報酬率

```{r}

df %>% 
  select(date,close,open,gold,death) %>% 
  mutate(
    gold = lag(gold,1) ,
    death = lag(death,1), 
    rate = close-open
  ) %>% 
  select(-death) %>% 
  mutate(
    return = (close - open)/open 
  ) %>% 
  na.omit() -> win

winrate = (nrow(win[win$rate>0,])/nrow(win[win$rate!=0,]) *100) 
  
  cat("winrate : " ,winrate)
  
  
win %<>%
  summarise(
    return = round(sd(return)*100,2) ,
    max(return) , 
    min(return)
)

```

```{r}

df %>% 
  select(date,close,open,gold,death) %>% 
  mutate(
    gold = lag(gold,1) ,
    death = lag(death,1), 
    rate = close-open
  ) %>% 
  select(-gold) %>% 
  mutate(
    return = (close - open)/open 
  ) %>% 
  na.omit() -> down

downrate = (nrow(down[down$rate>0,])/nrow(down[down$rate!=0,]) *100) 
  
  cat("winrate : " ,downrate)
  
  
down %<>%
  summarise(
    return = round(sd(return)*100,2) ,
    max(return) , 
    min(return)
)

```

```{r}

cat((downrate+winrate)/2)

```

